### ISSUE TITLE
Listening on Localhost only

### ISSUE THREAD

**Issue by antoine-collet** [dbpedia-spotlight/spotlight-docker#12]
Hello,
I was wondering why the service was listening only on localhost instead of 0.0.0.0 ?
As it is a containerized version the service is only accessible from the container itself
Thanks you

**Comment by sandroacoelho** [comment]
Hi @antoine-collet 

I'm not a network expert, but as far as I know, when we use  [-p 2222:80](https://docs.docker.com/engine/userguide/networking/default_network/binding/) , we open a port that redirects  all requests to the docker container. It means that you bind a listener to 0.0.0.0  or localhost. Also your have **--net=host** that creates a bridge with all opened ports available inside your container.

Hope it helps :)

**Comment by peternavr** [comment]
I've confirmed that you do need to allow it to listen on 0.0.0.0. I couldn't access the container out side of a kubernetes cluster until I rebuilt the image and did.

**Comment by sandroacoelho** [comment]
Hi @clanstyles , @antoine-collet 
I have changed the script to bind the listener to 0.0.0.0. Hope it helps!
btw: Docker HUB takes some hours to rebuild everything :+1: 

Best,

**Comment by antoine-collet** [comment]
@sandroacoelho Thank you !
