### ISSUE TITLE
Is there any way to disable the logs?

### ISSUE THREAD

**Issue by ghost** [dbpedia-spotlight/spotlight-docker#23]
There is a lot of logging output in the container. Could you provide a way to disable logging. We have tried setting the system properties log4.debug and log4j.configuration, they were applied, but without affect. Thank you.

**Comment by sandroacoelho** [comment]
Hi @weltallerdemensct,

There is an issue to fix it. From now, I advise you run docker using -d ( “detached” mode, in the background)

Best,
