### ISSUE TITLE
The supplied docker run arguments do not work

### ISSUE THREAD

**Issue by artreven** [dbpedia-spotlight/spotlight-docker#24]
It seems that the supplied in README arguments map port 2222 of the container, but the Dockerfile of the image specifies port 80, therefore for me the arguments to start the container are `-p 80:80`, **not** `-p 2222:80`.

**Comment by sandroacoelho** [comment]
Hi @artreven,

With Docker, it is possible to choose what port you want to use. We advise a high port in order to not conflict with reserved ports that are used by popular services, such as Apache, IIS and so on.

Best,
