### ISSUE TITLE
No Types Returned with Docker Spotlight

### ISSUE THREAD

**Issue by zdan12** [dbpedia-spotlight/spotlight-docker#40]
The dbpedia/dbpedia-spotlight docker image with the most recent "en" language model always returns empty types. This is different from the live API, which does return useful types, different similarity scores, and fewer entities.

Below, I pass the same query string to the Live API and Docker Image.
Notice how in both tests, I use the same text, the same confidence threshold - all parameters the same. But the responses are different. The docker image identifies "article" as an entity, the API does not. "Geneva" has many types on the live API, but has empty types on the docker image. The Similarity scores are also slightly different.

Types are important for my project, and I need the docker image's performance and reliability. Perhaps the Live API is running an older "en" language model that doesn't have this issue? How can I try running an older "en" language model in the docker image? Or perhaps types just aren't supported on the docker image? Any feedback here would be very appreciated.

**The Live API:**
RESPONSE
{
  "@text": "this is an article about Geneva and Myanmar.",
  "@confidence": "0.3",
  "@support": "0",
  "@types": "",
  "@sparql": "",
  "@policy": "whitelist",
  "Resources": [
    {
      "@URI": "http://dbpedia.org/resource/Geneva",
      "@support": "17157",
      "@types": "Wikidata:Q486972,Schema:Place,DBpedia:PopulatedPlace,DBpedia:Place,DBpedia:Location,DBpedia:Settlement",
      "@surfaceForm": "Geneva",
      "@offset": "25",
      "@similarityScore": "0.9981798618571678",
      "@percentageOfSecondRank": "0.0012774176800776215"
    },
...

**The Docker Image**
RESPONSE
{'@text': 'this is an article about Geneva and Myanmar.',
'@confidence': '0.3',
'@support': '0',
'@types': '',
'@sparql': '',
'@policy': 'whitelist',
'Resources': [
    {'@URI': 'http://dbpedia.org/resource/Article',
     '@support': '5163',
     '@types': '',
     '@surfaceForm': 'article',
     '@offset': '11',
     '@similarityScore': '0.895558085921875',
     '@percentageOfSecondRank': '0.04661536542968175'
    },
    {'@URI': 'http://dbpedia.org/resource/Geneva',
     '@support': '19011',
     '@types': '',
     '@surfaceForm': 'Geneva',
     '@offset': '25',
     '@similarityScore': '0.9978915725724677',
     '@percentageOfSecondRank': '0.0015876939459178352'
     },
...

**Comment by Julio-Noe** [comment]
Hello @zdan12,

This docker version of DBpedia Spotlight downloads the latest version of the selected language model, in this case, the English model.  

To run DBpedia Spotlight with an old language model version:

1. Create a new folder, e.g., dbpedia-local
```
mkdir  dbpedia-local
cd dbpedia-local
```
2. Download dbpedia-spotlight.jar
```
wget https://sourceforge.net/projects/spotlight-multilingual-docker/files/dbpedia-spotlight-1.1.jar
```
2. Download the desired version of the language model from the [Databus](https://databus.dbpedia.org/dbpedia/spotlight/spotlight-model/) (for this example it is downloading the 2021.06.25 - the same as the demo)
```
wget https://databus.dbpedia.org/dbpedia/spotlight/spotlight-model/2021.06.25/spotlight-model_lang=en.tar.gz
```
3.  untar the language model file
```
tar -xvf spotlight-model_lang\=en.tar.gz
```
4. run the DBpedia Spotlight service
```
java -Dfile.encoding=UTF-8 -Xmx15G -jar dbpedia-spotlight.jar en/ http://0.0.0.0:2222/rest
```
When you see the following output, the service will be ready
```
[main] INFO org.dbpedia.spotlight.web.rest.Server - Initiated 1 disambiguators.
[main] INFO org.dbpedia.spotlight.web.rest.Server - Initiated 2 spotters.
Dec 10, 2021 9:11:28 PM com.sun.grizzly.Controller logVersion
INFO: GRIZZLY0001: Starting Grizzly Framework 1.9.48 - 12/10/21, 9:11 PM
Server started in /home/jhernandez/dbpedia-local listening on http://0.0.0.0:2222/rest
[main] INFO org.dbpedia.spotlight.web.rest.Server -  Core threads: 5
[main] INFO org.dbpedia.spotlight.web.rest.Server -   Max threads: 5
[main] INFO org.dbpedia.spotlight.web.rest.Server - Max POST size: 2097152
```

5. Test the service
```
curl http://localhost:2222/rest/annotate \
    --data-urlencode "text=this is an article about Geneva and Myanmar" \
    --data "confidence=0.3" \
    -H "Accept: text/turtle"
```

My output was:

```
~$ curl http://localhost:2222/rest/annotate     --data-urlencode "text=this is an article about Geneva and Myanmar"     --data "confidence=0.2"  --data "support=0"   -H "Accept: text/turtle"
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .

<http://www.dbpedia-spotlight.com/#offset_11_18>
        a                       nif:Phrase , nif:OffsetBasedString ;
        nif:anchorOf            "article" ;
        nif:beginIndex          "11"^^xsd:nonNegativeInteger ;
        nif:endIndex            "18"^^xsd:nonNegativeInteger ;
        nif:referenceContext    <http://www.dbpedia-spotlight.com/#offset_0_43> ;
        itsrdf:taAnnotatorsRef  <http://www.dbpedia-spotlight.com> ;
        itsrdf:taClassRef       <http://dbpedia.org/ontology/Country> , <http://schema.org/Country> , <http://www.wikidata.org/entity/Q6256> , <http://dbpedia.org/ontology/Location> , <http://dbpedia.org/ontology/Place> , <http://schema.org/Place> , <http://dbpedia.org/ontology/PopulatedPlace> ;
        itsrdf:taConfidence     "0.40074620388085513"^^xsd:double ;
        itsrdf:taIdentRef       <http://dbpedia.org/resource/Morocco> .

<http://www.dbpedia-spotlight.com/#collection>
        a               nif:ContextCollection ;
        nif:hasContext  <http://www.dbpedia-spotlight.com/#offset_0_43> ;
        <http://purl.org/dc/terms/conformsTo>
                <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core/2.1> .

<http://www.dbpedia-spotlight.com/#offset_25_31>
        a                       nif:OffsetBasedString , nif:Phrase ;
        nif:anchorOf            "Geneva" ;
        nif:beginIndex          "25"^^xsd:nonNegativeInteger ;
        nif:endIndex            "31"^^xsd:nonNegativeInteger ;
        nif:referenceContext    <http://www.dbpedia-spotlight.com/#offset_0_43> ;
        itsrdf:taAnnotatorsRef  <http://www.dbpedia-spotlight.com> ;
        itsrdf:taClassRef       <http://dbpedia.org/ontology/Place> , <http://dbpedia.org/ontology/PopulatedPlace> , <http://www.wikidata.org/entity/Q486972> , <http://dbpedia.org/ontology/Settlement> , <http://schema.org/Place> , <http://dbpedia.org/ontology/Location> ;
        itsrdf:taConfidence     "0.9979568600705991"^^xsd:double ;
        itsrdf:taIdentRef       <http://dbpedia.org/resource/Geneva> .

<http://www.dbpedia-spotlight.com/#offset_36_43>
        a                       nif:Phrase , nif:OffsetBasedString ;
        nif:anchorOf            "Myanmar" ;
        nif:beginIndex          "36"^^xsd:nonNegativeInteger ;
        nif:endIndex            "43"^^xsd:nonNegativeInteger ;
        nif:referenceContext    <http://www.dbpedia-spotlight.com/#offset_0_43> ;
        itsrdf:taAnnotatorsRef  <http://www.dbpedia-spotlight.com> ;
        itsrdf:taClassRef       <http://dbpedia.org/ontology/PopulatedPlace> , <http://www.wikidata.org/entity/Q6256> , <http://dbpedia.org/ontology/Location> , <http://dbpedia.org/ontology/Place> , <http://schema.org/Country> , <http://schema.org/Place> , <http://dbpedia.org/ontology/Country> ;
        itsrdf:taConfidence     "0.9997650611279874"^^xsd:double ;
        itsrdf:taIdentRef       <http://dbpedia.org/resource/Myanmar> .

<http://www.dbpedia-spotlight.com/#offset_0_43>
        a               nif:OffsetBasedString , nif:Context ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "43"^^xsd:nonNegativeInteger ;
        nif:isString    "this is an article about Geneva and Myanmar" .
```

It also contains "article" but this time you have control over the version of the language model.  I hope this information helps you.

**Comment by zdan12** [comment]
Thank you very much @Julio-Noe, I'll try this out and let you know if it works!

**Comment by zdan12** [comment]
Hi @Julio-Noe, this works great and solved my problem! Thank you again for your super helpful response.

**Comment by Julio-Noe** [comment]
Perfect!!, @zdan12, I am glad to hear that it works.
