### ISSUE TITLE
404 on model download

### ISSUE THREAD

**Issue by Joel-PeakMetrics** [dbpedia-spotlight/spotlight-docker#45]
Hello,

The download of the model during docker startup is failing with a 404.

```
QUERY="PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
      PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
      PREFIX dct: <http://purl.org/dc/terms/>
      PREFIX dcat:  <http://www.w3.org/ns/dcat#>

      SELECT DISTINCT ?file WHERE {
        ?dataset dataid:artifact <https://databus.dbpedia.org/dbpedia/spotlight/spotlight-model> .
        ?dataset dcat:distribution ?distribution .
        {
                ?distribution dct:hasVersion ?latestVersion
                {
                        SELECT (?version as ?latestVersion) WHERE {
                                ?dataset dataid:artifact <https://databus.dbpedia.org/dbpedia/spotlight/spotlight-model> .
                                ?dataset dct:hasVersion ?version .
                        } ORDER BY DESC (?version) LIMIT 1
                }
                ?distribution dataid:contentVariant '$LANG'^^xsd:string .
        }
        ?distribution dcat:downloadURL ?file .
       }"
curl  -vvv --data-urlencode query="$QUERY" --data-urlencode format="text/tab-separated-values" https://databus.dbpedia.org/repo/sparql
```

Please advise.

TYIA!

**Comment by Julio-Noe** [comment]
Hi @Joel-PeakMetrics 

Thanks for the notification! I updated the QUERY variable as dataid prefixes were updated. Also, the SPARQL URL changed from https://databus.dbpedia.org/repo/sparql to https://databus.dbpedia.org/sparql. I did some tests, and all worked but if you find another issue, please don't hesitate to comment. Thanks again. Have a great day.

My best regards

Julio

**Comment by Joel-PeakMetrics** [comment]
Hello Julio,

I'm still receiving an error message, although the container does seem to start. Can you attempt to reproduce this?

```
$ docker run -P dbpedia/dbpedia-spotlight spotlight.sh en
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
Selected language: en
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1353  100   119  100  1234     26    279  0:00:04  0:00:04 --:--:--   306
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to downloads.dbpedia.org port 80: Connection refused
tar: can't open 'spotlight-model_lang=en.tar.gz': No such file or directory
rm: can't remove 'spotlight-model_lang=en.tar.gz': No such file or directory
/opt/spotlight/models/en http://0.0.0.0:80/rest/
```

**Comment by Julio-Noe** [comment]
Hello @Joel-PeakMetrics 

There is a problem with the Databus download service at this moment, or at least from my site because I am unable to download the English model. If you try to download the model 

http://downloads.dbpedia.org/repo/dbpedia/spotlight/spotlight-model/2022.03.01/spotlight-model_lang=en.tar.gz

you will not be able to reach the server. Let's wait until the problem is solved, and I will try your command again.

**UPDATE: The problem was fixed on the downloads.dbpedia.org server**

**Comment by Julio-Noe** [comment]
Hello @Joel-PeakMetrics 

I reproduced your command --`docker run -P dbpedia/dbpedia-spotlight spotlight.sh en`--  and it works fine. 

However, as a suggestion please refer to spotlight-docker documentation ([here](https://github.com/dbpedia-spotlight/spotlight-docker#available-language-models--quick-start-command) on the GitHub project) and consider the suggested command-line to execute the desired language, e.g., for English:

`docker run -tid --restart unless-stopped --name dbpedia-spotlight.en --mount source=spotlight-model,target=/opt/spotlight -p 2222:80 dbpedia/dbpedia-spotlight spotlight.sh en
`
If the port (`-p 2222:80`) is not defined you will, probably, have problems looking for the dynamic port assigned by docker. Thanks, and have a great day.
