### ISSUE TITLE
Dockerfile(s) no longer built because the debian:squeeze distribution is out of support

### ISSUE THREAD

**Issue by bobvdvelde** [dbpedia-spotlight/spotlight-docker#7]
It seems that the Dockerfiles rely on an old debian distribution which is no longer supported. In effect, the apt-get update and apt-get install steps fail. 

> root@b98d995f16a9:/# apt-get update  
Get:1 http://security.debian.org squeeze/updates Release.gpg [836 B]
Get:2 http://security.debian.org squeeze/updates Release [86.9 kB]
Ign http://httpredir.debian.org squeeze Release.gpg   
Ign http://httpredir.debian.org squeeze-updates Release.gpg
Ign http://httpredir.debian.org squeeze-lts Release.gpg
Get:3 http://security.debian.org squeeze/updates/main amd64 Packages [455 kB]  
Ign http://httpredir.debian.org squeeze Release                                     
Ign http://httpredir.debian.org squeeze-updates Release
Ign http://httpredir.debian.org squeeze-lts Release    
Err http://httpredir.debian.org squeeze/main amd64 Packages
  404  Not Found [IP: 80.84.224.198 80]
Err http://httpredir.debian.org squeeze-updates/main amd64 Packages
  404  Not Found [IP: 80.84.224.198 80]
Err http://httpredir.debian.org squeeze-lts/main amd64 Packages
  404  Not Found [IP: 80.84.224.198 80]
Fetched 543 kB in 0s (811 kB/s)
W: Failed to fetch http://httpredir.debian.org/debian/dists/squeeze/main/binary-amd64/Packages.gz  404  Not Found [IP: 80.84.224.198 80]
W: Failed to fetch http://httpredir.debian.org/debian/dists/squeeze-updates/main/binary-amd64/Packages.gz  404  Not Found [IP: 80.84.224.198 80]
W: Failed to fetch http://httpredir.debian.org/debian/dists/squeeze-lts/main/binary-amd64/Packages.gz  404  Not Found [IP: 80.84.224.198 80]
E: Some index files failed to download, they have been ignored, or old ones used instead.

In addition, current debian LTS repos no longer carry the openjdk-6-jre in the repository. 

> apt-get install -y openjdk-6-jre
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package openjdk-6-jre is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  icedtea-netx-common icedtea-netx
E: Package 'openjdk-6-jre' has no installation candidate
apt-get install -y openjdk-6-jre
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package openjdk-6-jre is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  icedtea-netx-common icedtea-netx
E: Package 'openjdk-6-jre' has no installation candidate

Unfortunately, the java scripts do not seem to be compatible with the openjdk-7-jre

> java -Dfile.encoding=UTF-8 -Xms3G -Xmx3G -jar -jar /opt/spotlight/dbpedia-spotlight-latest.jar /opt/spotlight/nl  http://localhost:80/rest
 INFO 2017-01-04 15:33:11,373 main [MemoryStore$] - Loading MemoryQuantizedCountStore...
 INFO 2017-01-04 15:33:11,464 main [MemoryStore$] - Done (89 ms)
 INFO 2017-01-04 15:33:11,464 main [MemoryStore$] - Loading MemoryTokenTypeStore...
 INFO 2017-01-04 15:33:11,692 main [MemoryTokenTypeStore] - Creating reverse-lookup for Tokens.
 INFO 2017-01-04 15:33:11,953 main [MemoryStore$] - Done (489 ms)
 INFO 2017-01-04 15:33:11,953 main [MemoryStore$] - Loading MemorySurfaceFormStore...
 INFO 2017-01-04 15:33:12,889 main [MemorySurfaceFormStore] - Summing total SF counts.
 INFO 2017-01-04 15:33:13,119 main [MemorySurfaceFormStore] - Creating reverse-lookup for surface forms, adding normalized surface forms.
 INFO 2017-01-04 15:33:13,331 main [MemoryStore$] - Done (1376 ms)
 INFO 2017-01-04 15:33:13,331 main [MemoryStore$] - Loading MemoryResourceStore...
Exception in thread "main" com.esotericsoftware.kryo.KryoException: Buffer underflow.
Serialization trace:
uriForID (org.dbpedia.spotlight.db.memory.MemoryResourceStore)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:162)
	at com.esotericsoftware.kryo.io.Input.readAscii_slow(Input.java:551)
	at com.esotericsoftware.kryo.io.Input.readAscii(Input.java:529)
	at com.esotericsoftware.kryo.io.Input.readString(Input.java:407)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$StringArraySerializer.read(DefaultArraySerializers.java:282)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$StringArraySerializer.read(DefaultArraySerializers.java:262)
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:702)
	at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:611)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:732)
	at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:157)
	at org.dbpedia.spotlight.db.memory.MemoryStore$.loadResourceStore(MemoryStore.scala:176)
	at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightModel.scala:54)
	at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.scala:66)
	at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.scala)
	at org.dbpedia.spotlight.web.rest.Server.initByModel(Server.java:297)
	at org.dbpedia.spotlight.web.rest.Server.main(Server.java:98)

Perhaps these issues can be mitigated with some minor revisions of the code?

**Comment by sandroacoelho** [comment]
Hi @bobvdvelde. Thanks for report it.

I have modified each file to use the image java:openjdk-6-jre. It works at docker hub. Could you please try again?

Btw: French model is not working as well. @jodaiber will fix it.

Best,

**Comment by sandroacoelho** [comment]
Hi @bobvdvelde, 

Have you tried after updating all images to java:openjdk-6-jre? 

Thanks,

**Comment by bobvdvelde** [comment]
Hi @sandroacoelho , 

Thanks for the quick response. I've finally gotten around to testing it, but I get a new error message:

>Sending build context to Docker daemon 4.608 kB
Step 1 : FROM java:openjdk-7-jre
 ---> 66125a354c32
Step 2 : MAINTAINER DBpedia Spotlight Team <dbp-spotlight-developers@lists.sourceforge.net>
 ---> Using cache
 ---> 912302460251
Step 3 : ENV RELEASE_SERVER www.dbpedia-spotlight.com
 ---> Using cache
 ---> 777f0ceb0acc
Step 4 : ENV RELEASE_FILENAME dbpedia-spotlight-latest.jar
 ---> Using cache
 ---> 3989b123f8be
Step 5 : ENV LANGUAGE_MODEL nl.tar.gz
 ---> Using cache
 ---> cf4f5fb54d76
Step 6 : RUN mkdir -p /opt/spotlight &&     cd /opt/spotlight &&     curl -O "http://$RELEASE_SERVER/$RELEASE_FILENAME" &&     curl -O "http://$RELEASE_SERVER/latest_models/$LANGUAGE_MODEL" &&     tar xvf $LANGUAGE_MODEL  &&     rm  $LANGUAGE_MODEL
 ---> Running in a2b89b58ab41
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99.4M  100 99.4M    0     0  1941k      0  0:00:52  0:00:52 --:--:-- 1848k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  184M  100  184M    0     0  2106k      0  0:01:29  0:01:29 --:--:-- 1708k
nl/
nl/spotter_thresholds.txt
nl/model.properties
nl/fsa_dict.mem
nl/README.txt
nl/stopwords.list
nl/model/
nl/model/tokens.mem
nl/model/quantized_counts.mem
nl/model/sf.mem
nl/model/candmap.mem
nl/model/context.mem
nl/model/res.mem
>
>gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
The command '/bin/sh -c mkdir -p /opt/spotlight &&     cd /opt/spotlight &&     curl -O "http://$RELEASE_SERVER/$RELEASE_FILENAME" &&     curl -O "http://$RELEASE_SERVER/latest_models/$LANGUAGE_MODEL" &&     tar xvf $LANGUAGE_MODEL  &&     rm  $LANGUAGE_MODEL' returned a non-zero code: 2

I think this is because the source .tar file is corrupted. 

In addition, the imported spotlight.sh for Dutch erroneously uses the path for Danish, so `/opt/spotlight/da` instead of `/opt/spotlight/nl`

**Comment by sandroacoelho** [comment]
Hi @bobvdvelde,
Apologies for the inconvenience and thanks for report it. Both issues are fixed. Could you please try again?
