### ISSUE TITLE
corrupt jarfile when run the portuguese language container

### ISSUE THREAD

**Issue by CedCannes** [dbpedia-spotlight/spotlight-docker#9]
An error occurs with the docker of the Portuguese language that I do not have with other languages.
I tested French and Italian without problem but for Portuguese I have :
`docker run -i -p 2230:80 dbpedia/spotlight-portuguese spotlight.sh`
-> 
`Error: Invalid or corrupt jarfile /opt/spotlight/dbpedia-spotlight-0.7.jar`

So I built the Portuguese version 7.1 for it to work

**Comment by sandroacoelho** [comment]
Hi @CedCannes ,

Thank you for the issue. I do not know what happened to our image at DockerHub. I just delete and recreate it, and now it works.

Best,

**Comment by CedCannes** [comment]
Yes, now it works, thank you very much. :smile:
